#!/usr/bin/env bash
# =============================================================
# Continuous Validation Runner — BRUTAL MODE
# =============================================================
# Runs Claude Code in an infinite loop with --dangerously-skip-permissions,
# validating and fixing everything until the codebase is PERFECT.
#
# This is NOT a gentle lint pass. This:
# - Checks compilation, lint, build
# - Scans for EVERY banned pattern (mocks, any, console.log, etc.)
# - Runs REAL tests against REAL infrastructure
# - Demands 100% test coverage
# - Writes missing tests using real PostgreSQL, Redis, Hedera Testnet
# - Checks security rules
# - Validates cross-references and documentation
# - Tops up Hedera testnet tokens if low
# - Repeats until EVERYTHING is clean or max iterations hit
#
# Usage:
#   ./scripts/continuous-validate.sh              # Default: 50 iterations
#   ./scripts/continuous-validate.sh 100          # 100 iterations
#   ./scripts/continuous-validate.sh 100 400      # 100 iterations, 400 max-turns
#
# Prerequisites:
#   - Claude Code CLI installed (`claude` command available)
#   - Docker running (for PostgreSQL + Redis)
#   - .env file configured with Hedera Testnet credentials
#   - Run from the project root directory
# =============================================================

set -euo pipefail

# ── Config ──
MAX_ITERATIONS=${1:-50}
MAX_TURNS=${2:-400}
LOG_DIR=".claude/state"
LOG_FILE="${LOG_DIR}/validation-runner.log"
VALIDATION_LOG="${LOG_DIR}/validation-log.md"
COOLDOWN=10

# ── Colors ──
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ── Banner ──
echo -e "${RED}${BOLD}"
echo "╔══════════════════════════════════════════════════╗"
echo "║     CONTINUOUS VALIDATION — BRUTAL MODE          ║"
echo "║     No mercy. No shortcuts. No fake tests.       ║"
echo "╠══════════════════════════════════════════════════╣"
echo -e "║  Iterations:  ${MAX_ITERATIONS}$(printf '%*s' $((35 - ${#MAX_ITERATIONS})) '')║"
echo -e "║  Turns/session: ${MAX_TURNS}$(printf '%*s' $((32 - ${#MAX_TURNS})) '')║"
echo -e "║  Mode: --dangerously-skip-permissions           ║"
echo "╚══════════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Preflight ──
if ! command -v claude &> /dev/null; then
  echo -e "${RED}ERROR: 'claude' CLI not found. Install Claude Code first.${NC}"
  exit 1
fi

if [ ! -f "CLAUDE.md" ]; then
  echo -e "${RED}ERROR: CLAUDE.md not found. Run this from the project root.${NC}"
  exit 1
fi

mkdir -p "$LOG_DIR"

# ── Initialize validation log ──
if [ ! -f "$VALIDATION_LOG" ]; then
  cat > "$VALIDATION_LOG" << 'INITLOG'
# Validation Log

> Auto-generated by continuous-validate.sh — BRUTAL MODE
> Each Claude Code session appends its findings below.
> Sessions read this log to avoid repeating work and to focus on unfixed issues.

---
INITLOG
fi

# ── Functions ──

ensure_docker() {
  echo -e "${CYAN}Ensuring Docker infrastructure is running...${NC}"
  if [ -f "docker-compose.test.yml" ]; then
    # Check if containers are healthy, restart if not
    PG_RUNNING=$(docker ps --filter "name=postgres" --format "{{.Status}}" 2>/dev/null || true)
    REDIS_RUNNING=$(docker ps --filter "name=redis" --format "{{.Status}}" 2>/dev/null || true)

    if [[ -z "$PG_RUNNING" || -z "$REDIS_RUNNING" ]]; then
      echo -e "${YELLOW}Restarting Docker containers...${NC}"
      docker compose -f docker-compose.test.yml down 2>/dev/null || true
      docker compose -f docker-compose.test.yml up -d 2>/dev/null || {
        echo -e "${RED}Docker compose failed — will retry next iteration${NC}"
        return 1
      }
      echo -e "${CYAN}Waiting 5s for containers to be ready...${NC}"
      sleep 5
    else
      echo -e "${GREEN}Docker containers already running${NC}"
    fi
  fi
  return 0
}

check_hedera_balance() {
  if [ -f ".env" ]; then
    OPERATOR_ID=$(grep -E '^HEDERA_OPERATOR_ID=' .env 2>/dev/null | cut -d= -f2 | tr -d '"' | tr -d "'" || true)
    if [ -n "$OPERATOR_ID" ]; then
      BALANCE_JSON=$(curl -s --max-time 10 "https://testnet.mirrornode.hedera.com/api/v1/accounts/${OPERATOR_ID}" 2>/dev/null || echo "")
      if [ -n "$BALANCE_JSON" ]; then
        BALANCE_TINYBAR=$(echo "$BALANCE_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('balance',{}).get('balance',0))" 2>/dev/null || echo "0")
        BALANCE_HBAR=$(echo "scale=2; $BALANCE_TINYBAR / 100000000" | bc 2>/dev/null || echo "0")
        echo -e "${CYAN}Hedera balance: ${BALANCE_HBAR} HBAR${NC}"

        # Top up if below 100 HBAR
        if [ "$(echo "$BALANCE_TINYBAR < 10000000000" | bc 2>/dev/null || echo "1")" = "1" ]; then
          echo -e "${YELLOW}Balance low — requesting faucet top-up...${NC}"
          for attempt in 1 2 3; do
            FAUCET_RESPONSE=$(curl -s --max-time 30 -X POST "https://faucet.hedera.com/api/v1/faucet" \
              -H "Content-Type: application/json" \
              -d "{\"address\": \"${OPERATOR_ID}\", \"network\": \"testnet\"}" 2>/dev/null || echo "")
            if echo "$FAUCET_RESPONSE" | grep -qi "success\|transferred"; then
              echo -e "${GREEN}Faucet top-up successful (attempt $attempt)${NC}"
              sleep 10  # Wait for balance to propagate
              break
            elif echo "$FAUCET_RESPONSE" | grep -qi "rate\|limit\|429\|too many"; then
              WAIT_TIME=$((60 * attempt))
              echo -e "${YELLOW}Faucet rate-limited — waiting ${WAIT_TIME}s (attempt $attempt/3)${NC}"
              sleep "$WAIT_TIME"
            else
              echo -e "${YELLOW}Faucet attempt $attempt failed: ${FAUCET_RESPONSE:0:100}${NC}"
              sleep 15
            fi
          done
        fi
      else
        echo -e "${YELLOW}Could not reach Hedera mirror node — will retry later${NC}"
      fi
    fi
  fi
}

# ── Start infrastructure ──
ensure_docker
check_hedera_balance

# ── Main loop ──
CONSECUTIVE_FAILURES=0

for i in $(seq 1 "$MAX_ITERATIONS"); do
  TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')

  echo ""
  echo -e "${YELLOW}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${YELLOW}${BOLD}  ITERATION $i / $MAX_ITERATIONS — $TIMESTAMP${NC}"
  echo -e "${YELLOW}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""

  # Re-check infrastructure every iteration (containers can crash overnight)
  ensure_docker

  # Re-check Hedera balance every 5 iterations (faucet has rate limits)
  if [ $((i % 5)) -eq 1 ]; then
    check_hedera_balance
  fi

  echo "[$TIMESTAMP] === ITERATION $i START ===" >> "$LOG_FILE"

  # ── Run Claude Code ──
  # set +e so a non-zero exit from Claude doesn't kill the loop
  set +e
  claude --dangerously-skip-permissions --max-turns "$MAX_TURNS" -p "
You are running in BRUTAL automated validation mode. Iteration $i of $MAX_ITERATIONS.

## YOUR MISSION

Find EVERY flaw. Fix EVERY flaw. Verify EVERY fix. Be ruthless.

## STEP 1: Read the rules and previous state

Read these files NOW before doing anything else:
- CLAUDE.md (ABSOLUTE LAWS — memorize them)
- .claude/skills/continuous-validation/SKILL.md (your full instruction set)
- .claude/state/validation-log.md (what previous iterations found — don't repeat, don't miss what they missed)
- .claude/rules/security.md (security rules to enforce)

## STEP 2: Follow the skill EXACTLY

The skill at .claude/skills/continuous-validation/SKILL.md has 8 phases. Execute ALL of them in order.

## KEY REMINDERS

ABSOLUTE LAW: NO MOCKING. NO FAKING. NO SIMULATING.
- If you find jest.fn(), jest.mock(), jest.spyOn() ANYWHERE — delete it and rewrite with real calls
- If you find a stub, fake, fixture, or test double — delete it and rewrite with real infrastructure
- If you find a test that doesn't actually test anything real — delete it and rewrite it
- If a test passes but doesn't hit real PostgreSQL/Redis/Hedera — it's a FAKE test, rewrite it

COVERAGE TARGET: 100%
- Check coverage with: pnpm test -- --coverage
- For every file below 100%, write new tests that cover the missing lines
- Tests MUST use real infrastructure (Docker PostgreSQL on port 5433, Redis on 6380 per docker-compose.test.yml)
- If Hedera testnet balance is low, hit the faucet: POST https://faucet.hedera.com/api/v1/faucet
- If faucet is rate-limited (429), wait 60s and retry up to 3 times

HANDLE REAL BLOCKERS:
- Docker container crashed? Run: docker compose -f docker-compose.test.yml restart
- Hedera testnet unreachable? Run ALL non-Hedera checks, log the blocker, do NOT fake results
- pnpm install fails? Try --prefer-offline, wait 30s and retry
- If ANY infrastructure is down, still run every check that doesn't need it
- NEVER mark VALIDATION_CLEAN if any test was skipped due to infrastructure

EVERY RULE MATTERS:
- Zero \`: any\` types
- Zero \`console.log\` in production code
- Zero \`@ts-ignore\`
- Zero hardcoded secrets/URLs/Hedera IDs
- Zero generic \`throw new Error()\` — use typed exceptions
- Zero empty catch blocks
- Every Hedera transaction has maxTransactionFee set
- All config from ConfigService/env vars

## STEP 3: Update the validation log

Before your session ends, append your findings to .claude/state/validation-log.md using the format in the skill.
Write VALIDATION_CLEAN only if EVERYTHING passes with zero issues.

## STEP 4: If previous iteration was VALIDATION_CLEAN

Run the FULL pipeline again to confirm. If it's still clean after a complete re-run, write VALIDATION_CLEAN again and exit.
Two consecutive VALIDATION_CLEAN = we're done.
" 2>&1 | tee -a "$LOG_FILE"

  SESSION_EXIT=${PIPESTATUS[0]}
  set -e
  echo "" >> "$LOG_FILE"
  echo "[$TIMESTAMP] Iteration $i exit code: $SESSION_EXIT" >> "$LOG_FILE"

  # ── Handle session failures ──
  if [ "$SESSION_EXIT" -ne 0 ]; then
    CONSECUTIVE_FAILURES=$((CONSECUTIVE_FAILURES + 1))
    echo -e "${RED}Session exited with code $SESSION_EXIT (failure $CONSECUTIVE_FAILURES)${NC}"

    if [ "$CONSECUTIVE_FAILURES" -ge 3 ]; then
      # 3 consecutive failures — longer cooldown, restart Docker
      echo -e "${RED}3 consecutive failures — restarting infrastructure and waiting 120s...${NC}"
      docker compose -f docker-compose.test.yml down 2>/dev/null || true
      sleep 10
      docker compose -f docker-compose.test.yml up -d 2>/dev/null || true
      sleep 120
      CONSECUTIVE_FAILURES=0
    elif [ "$CONSECUTIVE_FAILURES" -ge 2 ]; then
      # 2 consecutive failures — medium cooldown
      echo -e "${YELLOW}2 consecutive failures — waiting 60s before retry...${NC}"
      sleep 60
    else
      # Single failure — short cooldown
      echo -e "${YELLOW}Session failed — waiting 30s before retry...${NC}"
      sleep 30
    fi

    # Check if failure might be rate limiting (Claude API)
    if tail -5 "$LOG_FILE" | grep -qi "rate.limit\|429\|too many requests\|overloaded"; then
      RATE_WAIT=180
      echo -e "${RED}Possible API rate limit detected — waiting ${RATE_WAIT}s...${NC}"
      echo "[$TIMESTAMP] Rate limit detected, waiting ${RATE_WAIT}s" >> "$LOG_FILE"
      sleep "$RATE_WAIT"
    fi

    continue
  fi

  # Session succeeded — reset failure counter
  CONSECUTIVE_FAILURES=0

  # ── Check for clean status ──
  # Need TWO consecutive VALIDATION_CLEAN to actually stop
  CLEAN_COUNT=$(tail -50 "$VALIDATION_LOG" | grep -c "VALIDATION_CLEAN" || true)

  if [ "$CLEAN_COUNT" -ge 2 ]; then
    echo ""
    echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║          VALIDATION PASSED — ALL CLEAN            ║${NC}"
    echo -e "${GREEN}${BOLD}║     Confirmed clean on 2 consecutive passes       ║${NC}"
    echo -e "${GREEN}${BOLD}║          Iterations used: $i$(printf '%*s' $((25 - ${#i})) '')║${NC}"
    echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "[$TIMESTAMP] CONFIRMED CLEAN after $i iterations (2 consecutive passes)" >> "$LOG_FILE"
    exit 0
  fi

  if [ "$i" -lt "$MAX_ITERATIONS" ]; then
    echo -e "${CYAN}Cooling down ${COOLDOWN}s before next iteration...${NC}"
    sleep "$COOLDOWN"
  fi
done

# ── Max iterations reached ──
echo ""
echo -e "${RED}${BOLD}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${RED}${BOLD}║      MAX ITERATIONS ($MAX_ITERATIONS) REACHED               ║${NC}"
echo -e "${RED}${BOLD}║  Check: .claude/state/validation-log.md          ║${NC}"
echo -e "${RED}${BOLD}║  Check: .claude/state/validation-runner.log      ║${NC}"
echo -e "${RED}${BOLD}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo "[$(date '+%Y-%m-%d %H:%M:%S')] MAX ITERATIONS REACHED" >> "$LOG_FILE"
exit 1
