import { DataSource } from "typeorm";
import * as dotenv from "dotenv";
import {
  UserEntity,
  BusinessProfileEntity,
  ConversationEntity,
  ConversationMemberEntity,
  MessageIndexEntity,
  SocialFollowEntity,
  FollowerCountEntity,
  PostIndexEntity,
  PostLikeEntity,
  PostCommentEntity,
  FeedItemEntity,
  PaymentIndexEntity,
  PlatformTopicEntity,
  OrganizationEntity,
  OrganizationMemberEntity,
  OrganizationInvitationEntity,
  PaymentRequestEntity,
  TransactionEntity,
  NotificationEntity,
  BroadcastMessageEntity,
  BroadcastSubscriptionEntity,
} from "./entities";

dotenv.config({ path: "../../.env" });

export const AppDataSource = new DataSource({
  type: "postgres",
  host: process.env.DB_HOST || "localhost",
  port: parseInt(process.env.DB_PORT || "5432", 10),
  username: process.env.DB_USERNAME || "hedera_social",
  password: process.env.DB_PASSWORD || "",
  database: process.env.DB_DATABASE || "hedera_social",
  synchronize: false,
  logging: process.env.NODE_ENV === "development",
  entities: [
    UserEntity,
    BusinessProfileEntity,
    ConversationEntity,
    ConversationMemberEntity,
    MessageIndexEntity,
    SocialFollowEntity,
    FollowerCountEntity,
    PostIndexEntity,
    PostLikeEntity,
    PostCommentEntity,
    FeedItemEntity,
    PaymentIndexEntity,
    PlatformTopicEntity,
    OrganizationEntity,
    OrganizationMemberEntity,
    OrganizationInvitationEntity,
    PaymentRequestEntity,
    TransactionEntity,
    NotificationEntity,
    BroadcastMessageEntity,
    BroadcastSubscriptionEntity,
  ],
  migrations: ["src/database/migrations/**/*.ts"],
  subscribers: [],
});

export default AppDataSource;
